### PR TITLE
Add Zsh completion instructions

### PR DESCRIPTION
**Pull request by sapegin**
#35

### CODE REVIEW

**Comment by jamiew** [comment]
Props for all the awesome PRs this week

I am AFK until end of week but will review then if nobody beats me to them... sorry for the delay!

**Comment by sapegin** [comment]
@jamiew Looks like your weeks are long ;-|

**Comment by jamiew** [comment]
Sorry, started a new job

Does this depend on another zsh library? I'm not a zsh user and think I am doing this wrong. Followed README but get complaints about `compdef`

**Comment by sapegin** [comment]
I don’t think so:

```
❯ type compdef
compdef is a shell function from /usr/local/Cellar/zsh/5.3.1_1/share/zsh/functions/compinit
```

**Comment by sapegin** [comment]
> Sorry, started a new job

Sounds cool, I’m going to do that in January ;-)

**Comment by jamiew** [comment]
Congrats :)

So I've tried installing a newer `zsh` and `zsh-completions` using Homebrew (and followed the basic post-install instructions) but still no dice. 

Could you share a copy of your .zshrc? Here's mine so far:

```
echo "Loading .zshrc..."

# From homebrew zsh-completions post-install
fpath=(/usr/local/share/zsh-completions $fpath)

# From Artem
fpath=($(brew --prefix)/share/zsh/functions $fpath)
autoload -Uz _git && _git
compdef __git_branch_names branch
```

**Comment by jamiew** [comment]
Oh and the output from your sample:

```
\w$(__git_ps1 '()')$ type compdef
compdef not found
```

(I have no idea where that PS1 is coming from... thought it might be loading my `.bashrc` or `.bash_profile` for some reason but confirmed it's not)

**Comment by sapegin** [comment]
Here it is: https://github.com/sapegin/dotfiles/blob/master/tilde/zshrc.zsh

**Comment by jamiew** [comment]
OK, with `oh-my-zsh` and your `zshrc` (and your cool theme!) it works... I'll try to work backwards and see if I can find what the dependency is

Then would just add that to the README?

**Comment by sapegin** [comment]
@jamiew I think we should finally merge this? ;-/

**Comment by jamiew** [comment]
Good for me, go for it!

**Pull request merged**
