### PR TITLE
[RFC] Emojification 🦄

### PR DESCRIPTION
**Pull request by sapegin**
What do you think? 

image 2016-10-12 at 9 56 52 am

### CODE REVIEW

**Comment by jamiew** [comment]
Haha nice, I like it! @jm3 any feels/suggestions here?

**Comment by jm3** [comment]
haven't tried it yet but 🍤🍒🍇🔥⭐️

**Comment by jamiew** [comment]
Merge away my friend

If anyone complains maybe we just add an env var? but I'd wait for the
complaints :)

**Comment by sapegin** [comment]
I’ll see if I can emojify other scripts ⛺️

**Comment by sapegin** [comment]
I’ve emojified all other scripts. Any objections? ;-)

**Comment by jamiew** [comment]
I don't think you'll find them here :) Great work

**Pull request merged**
