### PR TITLE
Push: Fix parent brach for new branches

### PR DESCRIPTION
**Pull request by sapegin**
Often compare URL is wrong:

1. When branch isn’t based on master
2. When you push to a fork and press “Create pull request” button it’ll create a PR to your own fork instead of the original project.

image 2017-09-21 at 4 45 09 pm

### CODE REVIEW

**Comment by sapegin** [comment]
@jamiew What do you think? ;-)

**Comment by jamiew** [comment]
Checking this out now

**Comment by jamiew** [comment]
So I still find it useful having specific compare URLs – the diff of what was there and what just got pushed basically – what's the argument for just copying full project URL?

e.g. with this patch I push and get: 

```
https://github.com/jamiew/random-test-repo
```

whereas previously I'd get something more like:

```
https://github.com/jamiew/random-test-repo/compare/3402a6d...0076d2a
```

which is what I'd share in e.g. an issue comment.

Arguably a more pull request-y style URL would be better? Maybe out of scope or excessively GitHub-specific?

**Comment by sapegin** [comment]
The problem with compare URLs:

1. I don’t know any use case where it would be useful ;-)
2. There are wrong or misleading at least in this two cases I’ve mentioned in the description.

**Comment by jamiew** [comment]
Would you use the output of this revised version, copying the full repo URL to your clipboard? I do actually use the compare URLs all the time (it's actually where this whole project started) but curious if I'm the only one!

The "doesn't work if not based on master" seems like a bug that shouldn't really happen, since it's supposed to be diff'ing two SHA-1's, not any actual branch names (I think)

**Comment by sapegin** [comment]
Most of the time I use pull requests to share code, that‘s why the current link doesn’t work for me ;-)

Probably we can keep both and print project URL as a plain text. I don‘t use clipboard feature anyway — it‘s faster to cmd+click the URL ;-) 

It would be super cool to have a create PR link but I’m not sure it will be easy to implement.

**Comment by sapegin** [comment]
I see that is always compare new branches with `master`:

https://github.com/jamiew/git-friendly/blob/50d3e8c6feea9e5cc32267ff56e8851a28bfe38d/push#L36-L39

That’s the reason for 1 I think. We should compare with a parent branch.

**Comment by sapegin** [comment]
@jamiew I’ve reverted my initial changes and instead fix the parent branch issue (1). Not sure we can fix the second issue.

**Comment by sapegin** [comment]
@jamiew What do you think now? ;-)

**Comment by jamiew** [comment]
Sorry, slow uptake

Testing this out I was able to get it to break and give me a bad compare URL:

```
https://github.com/jamiew/random-test-repo/compare/...deploys
```

Trying to replicate since I'm not positive how I got there

**Comment by jamiew** [comment]
I cannot replicate the above soooooo... think it's good to go

My basic test case:

```
branch master
branch test1
git commit --allow-empty -m "Make sure it's different"
push
```

Works, produces `master...test1`

```
branch master
branch test1
git commit --allow-empty -m "Make sure it's different"
branch test2
git commit --allow-empty -m "Make sure it's different"
push
```

Works, produces `test1...test2`

**Comment by sapegin** [comment]
We can fallback to `master` just in case.

**Comment by jamiew** [comment]
Looks good but needs merge conflict resolution

**Comment by sapegin** [comment]
Done ;-)

**Pull request merged**
